#!/bin/bash

tmux new-session -d -s dev -n main 'cd ~/prj/biokostas/cpgenius/ && uv run uvicorn app.start_fastapi:app --host 0.0.0.0 --port 8001 --reload; zsh' \; \
  split-window -h 'cd ~/prj/biokostas/cpgenius/ && uv run celery -A app.celery_tasks worker -l INFO; zsh' \; \
  split-window -v 'htop; bash' \; \
  select-pane -t 0 \; \
  split-window -v 'mpv "$(sed -n '6p' ~/radio_stations.txt)"; bash' \; \
  select-pane -t 0 \; \
  attach-session -t dev
